image:
  file: .gitpod.Dockerfile

tasks:
  - name: serve docs
    init: gp sync-await docs
    command: miniserve --index benimator/index.html target/doc

  - name: test
    init: |
      cp .cargo/fast_compiles_config .cargo/config.toml
      cargo update
      cargo +nightly doc --all-features --no-deps
      gp sync-done docs
      cargo clippy --all-features --all-targets
      cargo test --all-features
      cargo test
    command: |
      cargo watch -x 'test --tests' -x 'test --features bevy-07' -x 'test --all-features' -x 'clippy --all-features --all-targets' -x '+nightly doc --all-features --no-deps'

vscode:
  extensions:
    - belfz.search-crates-io
    - matklad.rust-analyzer
    - serayuzgur.crates
    - bungcip.better-toml
    - valmack.circleci-config-validator

ports:
  - name: documentation
    port: 8080
    visibility: private
    onOpen: notify

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: false
