image:
  file: .gitpod.Dockerfile

tasks:
  - name: test
    init: |
      cp .cargo/fast_compiles_config .cargo/config.toml
      cargo update
      cargo test --all-features
      cargo test
      gp sync-done test
      cargo clippy --all-features --all-targets
      cargo doc --all-features --no-deps
    command: |
      cargo watch \
        -x 'test --tests' \
        -x 'test --all-features --tests' \
        -x 'test --all-features' \
        -x 'clippy --all-features --all-targets' \
        -x 'doc --all-features --no-deps'

  - name: example
    init: |
      gp sync-await test
      cargo build --target wasm32-unknown-unknown --example readme
    command: cargo run --target wasm32-unknown-unknown --example readme

vscode:
  extensions:
    - belfz.search-crates-io
    - matklad.rust-analyzer
    - serayuzgur.crates
    - bungcip.better-toml

ports:
  - name: example (wasm)
    port: 1334
    visibility: private
    onOpen: notify

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: false
