image: gitpod/workspace-full-vnc

tasks:
  - before: rustup component add clippy
    init: |
      cargo update
      cargo clippy --all-features --all-targets
      cargo test --all-features
      cargo doc --all-features --no-deps
    command: cargo watch -x 'test --all-features' -x 'clippy --all-features --all-targets' -x 'doc --all-features --no-deps'

vscode:
  extensions:
    - belfz.search-crates-io
    - matklad.rust-analyzer
    - serayuzgur.crates
    - bungcip.better-toml

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: false
