allow-branch = ["main"]
pre-release-commit-message = "release {{version}}"

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "## \\[Unreleased\\]"
replace = "## [Unreleased]\n\n\n## [{{version}}] - {{date}}"
prerelease = true
exactly = 1

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "\\.\\.\\.HEAD"
replace = "...v{{version}}"
prerelease = true
exactly = 1

[[pre-release-replacements]]
file = "CHANGELOG.md"
search = "\\[Unreleased\\]:"
replace = "[Unreleased]: https://github.com/jcornaz/beancount-parser/compare/v{{version}}...HEAD\n[{{version}}]:"
prerelease = true
exactly = 1
