name: bevy-main

on:
  schedule:
    - cron: '0 0 */3 * *'

  pull_request:
    paths:
      - '.github/workflows/bevy-main.yml'

jobs:
  bevy-main:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: bevy-main

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - run: cargo test --all-features
