name: release

on:
  schedule:
   - cron: '0 0 * * 1,5'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack@0.5,just@1,cargo-msrv@0.15,cargo-deny@0.13,cargo-edit@0.11
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: just release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
