name: release

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt
      - uses: taiki-e/install-action@cargo-binstall
      - uses: taiki-e/install-action@cargo-hack
      - uses: taiki-e/install-action@just
      - run: cargo binstall --no-confirm cargo-edit
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: just release
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
